# encoding: utf-8
# This file originally created at http://rove.io/1a54ff42ed4249fb55f72a2d5b9322e5

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  #config.vm.box = "opscode-ubuntu-12.04_chef-11.4.0"
  #config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.0.box"
  config.ssh.forward_agent = true

  config.vm.synced_folder "../server", "/home/vagrant/server"
  config.vm.network :forwarded_port, guest: 8080, host: 8080

 config.vm.provision :shell, path: "bootstrap.sh"

#  config.vm.provision :chef_solo do |chef|
#    chef.cookbooks_path = ["cookbooks"]
#    chef.add_recipe 'mongodb'
#    chef.add_recipe :apt
#    chef.add_recipe 'vim'
#    chef.add_recipe 'git'
#    chef.add_recipe 'ruby_build'
#    chef.add_recipe 'rbenv::user'
#    chef.json = {
#      :git   => {
#        :prefix => "/usr/local"
#      },
#      :rbenv => {
#        :user_installs => [
#          {
#            :user   => "vagrant",
#            :rubies => [
#              "2.1.5"
#            ],
#            :global => "2.1.5"
#          }
#        ]
#      }
#    }
#  end
end
