# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.ssh.forward_agent = true

  config.vm.synced_folder "../server", "/home/vagrant/server"
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  config.vm.provision :shell, path: "bootstrap.sh"
end
